# Config File

WIDTH, HEIGHT = 1200, 900
FPS = 60
TOP_LANE_HEIGHT, BOTTOM_LANE_HEIGHT = HEIGHT * 0.75, HEIGHT * 0.25
BASE_WIDTH_INSET = 0.05
LEFT_BASE_X, RIGHT_BASE_X = WIDTH * BASE_WIDTH_INSET, WIDTH - (WIDTH * BASE_WIDTH_INSET)
BOT_TEST_CONFIG = {
    "health" : 100,
    "damage" : 10,
    "speed" : 1.25
}
VIEWPORT_MAX_WIDTH, VIEWPORT_MAX_HEIGHT = WIDTH * 6, HEIGHT * 2
NAVBOX_WIDTH, NAVBOX_HEIGHT = VIEWPORT_MAX_WIDTH * 0.06, TOP_LANE_HEIGHT * 0.10